# Generated by Django 4.1.3 on 2022-11-14 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ContentTemplate',
                'verbose_name_plural': 'ContentTemplates',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NumberGroup',
                'verbose_name_plural': 'NumberGroups',
                'ordering': ['-created_at'],
            },
        ),
    ]
