# Generated by Django 4.1.3 on 2022-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_sendmessagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessagemodel',
            name='customers',
        ),
        migrations.AddField(
            model_name='sendmessagemodel',
            name='phone_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
