# Generated by Django 4.1.3 on 2022-11-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sendmessagemodel_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessagemodel',
            name='phone_field',
        ),
        migrations.AddField(
            model_name='sendmessagemodel',
            name='customers',
            field=models.ManyToManyField(blank=True, to='api.customer'),
        ),
    ]
