# Generated by Django 4.1.3 on 2022-11-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sendmessagemodel_phone_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state_code',
        ),
    ]
