# Generated by Django 4.1.3 on 2022-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_contenttemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
